Feature/homework3
AlexKozhan/mypymar2024 pull request #1
Opened 2024-05-03 08:49 UTC by AlexKozhan

2024-05-03 10:11 UTC, Stml89 commented
Please correct PR name.

JFYI:
Start using English for commit messages and comments

2024-05-03 10:12 UTC, Stml89 requested changes

2024-05-03 12:03 UTC, AlexKozhan commented on .github/workflows/ithub-actions-demo.yml
Removed file ".github/workflows/ithub-actions-demo.yml"
Changed PR name

2024-05-03 12:40 UTC, AlexKozhan commented
Did i succeed?

2024-05-04 09:29 UTC, Stml89 approved these changes
Approved

2024-05-04 09:30 UTC, Stml89 commented
Now you can merge it to the master branch

2024-05-04 10:19 UTC, merged