Homework7: Alexey Kozhan
AlexKozhan/mypymar2024 pull request #11
Opened 2024-05-21 12:24 UTC by AlexKozhan

Did homework in 3 Python Files

2024-05-21 14:59 UTC, AlexKozhan commented on homework1.py
> +    KOLVO_BYKI = 0
> Why is this variable in the uppercase?

there was linter error with uppercase

2024-05-21 15:06 UTC, AlexKozhan commented on homework1.py
> +    KOLVO_BYKI = 0
homework1.py:39:4: C0103: Constant name "kolvo_byki" doesn't conform to UPPER_CASE naming style (invalid-name)

2024-05-21 15:06 UTC, AlexKozhan commented on homework1.py
> +    KOLVO_BYKI = 0
> Why is this variable in the uppercase?

homework1.py:39:4: C0103: Constant name "kolvo_byki" doesn't conform to UPPER_CASE naming style (invalid-name)

2024-05-21 15:17 UTC, AlexKozhan commented on homework1.py
> +    Chislo_Igroka = input("Введи 4-значное число с неповторяющимися цифрами ")
> chislo_igroka

fixed

2024-05-23 19:35 UTC, Stml89 requested changes

2024-05-23 19:35 UTC, Stml89 commented on homework2.py
> +    probeli = N-i-1
change 'probeli' to spaces. Please start use English language

2024-05-23 19:35 UTC, Stml89 commented on homework3.py
> +print(f"Не хватает {len(MISSING_STATUI_STRING)} статуй")
it will count the whole string, e.g.: comma and spaces

2024-05-23 20:14 UTC, AlexKozhan commented on homework3.py
> +print(f"Не хватает {len(MISSING_STATUI_STRING)} статуй")
fixed

> it will count the whole string, e.g.: comma and spaces

2024-05-23 20:14 UTC, AlexKozhan commented on homework2.py
> +    probeli = N-i-1
> change 'probeli' to spaces. Please start use English language

fixed

2024-05-28 19:58 UTC, Stml89 approved these changes

2024-07-09 18:09 UTC, merged