homework8 is done in 3 Python files
AlexKozhan/mypymar2024 pull request #12
Opened 2024-05-27 13:14 UTC by AlexKozhan

2024-05-31 20:41 UTC, AlexKozhan commented on homework1.py
> +print(strictly_increasing_without_one_element(solution1))
> pls, use assert instead of print()

fixed

2024-06-01 17:22 UTC, Stml89 requested changes

2024-06-01 17:22 UTC, Stml89 commented on homework1.py
> +assert strictly_increasing_without_one_element(solution1)
what does this `assert` verify?

use of assert is following:
`assert <statement> <logical operatos> <expected value>, <error message>`
e.g.:
`assert strictly_increasing_without_one_element(solutions) == True, <error message>`

https://www.w3schools.com/python/ref_keyword_assert.asp

2024-06-01 18:01 UTC, AlexKozhan commented on homework1.py
> +assert strictly_increasing_without_one_element(solution1)
> what does this `assert` verify?
> 
> use of assert is following: `assert <statement> <logical operatos> <expected value>, <error message>` e.g.: `assert strictly_increasing_without_one_element(solutions) == True, <error message>`
> 
> https://www.w3schools.com/python/ref_keyword_assert.asp

i did like this, but there were linter errors with asserting to True,
 E712 Avoid equality comparisons to `True`; use `if strictly_increasing_without_one_element(solution1):` for truth checks

2024-06-01 19:58 UTC, Stml89 reviewed
fix comment and you can merge PR

2024-06-01 19:58 UTC, Stml89 commented on homework1.py
> +assert strictly_increasing_without_one_element(solution1)
you are right, then do following:
```
assert <statement>, <error message>
```

2024-06-01 19:58 UTC, Stml89 approved these changes

2024-06-06 20:35 UTC, Stml89 commented
to be able to merge it you have to resolve conflicts first, ask for help if you need it

2024-07-09 17:58 UTC, merged