Homework10: Alexey Kozhan
AlexKozhan/mypymar2024 pull request #14
Opened 2024-06-05 14:19 UTC by AlexKozhan

Homework is done in 4 python files

2024-06-07 20:59 UTC, Stml89 approved these changes

2024-06-07 20:59 UTC, Stml89 commented on homework1.py
> +                raise ValueError('Введите положительные числа')
```suggestion
            if i < 0:
                raise ValueError('Числа должны быть положительными')
```

2024-06-07 20:59 UTC, Stml89 commented on homework4.py
Nice!

2024-06-07 20:59 UTC, Stml89 commented on homework2.py
> +            return None
return False

2024-06-07 20:59 UTC, Stml89 commented on homework2.py
You are using the same filename, so git shows the difference. Please, create files with different filenames

2024-06-08 13:28 UTC, AlexKozhan commented on homework1.py
> +                raise ValueError('Введите положительные числа')
fixed

2024-06-08 13:28 UTC, AlexKozhan commented on homework2.py
> +            return None
fixed

2024-06-08 13:28 UTC, AlexKozhan commented on homework2.py
fixed

2024-06-08 13:28 UTC, AlexKozhan commented on homework4.py
ty

2024-06-11 21:20 UTC, Stml89 requested changes

2024-06-11 21:20 UTC, Stml89 commented on resultati.py
> +    return a + b
1 function should work the same for numbers and letters
```suggestion
@validate_type
def plus_two_value(a, b):
    """Function for concatenating two values"""
    return a + b
```

2024-06-12 12:13 UTC, AlexKozhan commented on resultati.py
> +    return a + b
fixed

2024-06-16 15:44 UTC, Stml89 approved these changes

2024-07-09 18:14 UTC, merged