Homework11: Alexey Kozhan
AlexKozhan/mypymar2024 pull request #15
Opened 2024-06-06 12:10 UTC by AlexKozhan

Homework11 is done in 2 python files

2024-06-08 07:31 UTC, Stml89 commented
Please use different filenames, not `homework1.py`, `homework2.py` and etc

2024-06-08 07:33 UTC, Stml89 requested changes
See comment above

2024-06-08 13:34 UTC, AlexKozhan commented
> Please use different filenames, not `homework1.py`, `homework2.py` etc, because those files are already in the repo and git shows the differences between previous and current homework

fixed

2024-06-08 13:34 UTC, AlexKozhan commented
> See comment above

fixed

2024-06-16 06:58 UTC, Stml89 requested changes

2024-06-16 06:58 UTC, Stml89 commented on deposit_2.py
> +    def display_deposit_info(self):
please use `__str__` method instead

2024-06-16 06:58 UTC, Stml89 commented on deposit_2.py
> +        return a
You do not need to create so many variables:
```suggestion
return money * (1 + annual_rate / n) ** (n * duration)
```

2024-06-16 06:58 UTC, Stml89 commented on deposit_2.py
> +        pass
What is the purpose of this method here if it does not do anything?

2024-06-16 06:58 UTC, Stml89 commented on deposit_2.py
> +    def calculate_final_money(self, money: float, duration: int,
use staticmethod here 
https://www.programiz.com/python-programming/methods/built-in/staticmethod

2024-06-16 06:58 UTC, Stml89 commented on library_1.py
> +    def return_book(self, book):
use staticmethod here
https://www.programiz.com/python-programming/methods/built-in/staticmethod

2024-06-16 06:58 UTC, Stml89 commented on library_1.py
> +    def return_book(self):
```
user1.reserve_book(book1)
user1.take_book(book1)
user2.return_book(book1)
```
Book1 was taken by user1, but user2 can return it

2024-06-16 12:44 UTC, AlexKozhan commented on deposit_2.py
> +    def display_deposit_info(self):
fixed

2024-06-16 12:44 UTC, AlexKozhan commented on deposit_2.py
> +        return a
fixed, ty

2024-06-16 12:44 UTC, AlexKozhan commented on deposit_2.py
> +    def calculate_final_money(self, money: float, duration: int,
fixed

2024-06-16 12:44 UTC, AlexKozhan commented on library_1.py
> +    def return_book(self, book):
fixed

2024-06-16 12:44 UTC, AlexKozhan commented on library_1.py
> +    def return_book(self):
fixed, i guess

2024-06-16 12:46 UTC, AlexKozhan commented on deposit_2.py
> +        pass
there were linter erros when i drafted the PR, one of them stated that there is few methods (only 1) in class Deposit so there must be  at least another, so i did

2024-06-16 18:06 UTC, Stml89 approved these changes

2024-07-09 17:57 UTC, merged