Homework12: Alexey Kozhan
AlexKozhan/mypymar2024 pull request #16
Opened 2024-06-13 10:40 UTC by AlexKozhan

Homework12 is done in 3 files

2024-06-16 17:28 UTC, Stml89 requested changes

2024-06-16 17:28 UTC, Stml89 commented on cards.py
> +        if 0 <= index < len(self.cards):
Better to move this check `0 < X < len()` to where you ask user for a number

2024-06-16 17:28 UTC, Stml89 commented on converter.py
> +    # pylint: disable=too-few-public-methods
Please, use `.pylintrc` file

2024-06-16 17:28 UTC, Stml89 commented on himiya.py
> +    def __init__(self):
do you really need this method?

2024-06-16 17:28 UTC, Stml89 commented on himiya.py
> +    def multiply_current(self, current: Dict[str, int], num: int):
Use `@staticmethod`

2024-06-16 17:28 UTC, Stml89 commented on himiya.py
> +class Himiya:
Chemistry

2024-06-16 19:33 UTC, AlexKozhan commented on cards.py
> +        if 0 <= index < len(self.cards):
fixed

2024-06-16 19:34 UTC, AlexKozhan commented on converter.py
> +    # pylint: disable=too-few-public-methods
fixed

2024-06-16 19:35 UTC, AlexKozhan commented on himiya.py
> +    def __init__(self):
there was pylint too-few public methods error again as in homework11. Created .pylintrc file - next time i will not create such methods. so - fixed.

2024-06-16 19:36 UTC, AlexKozhan commented on himiya.py
> +    def multiply_current(self, current: Dict[str, int], num: int):
fixed

2024-06-16 19:36 UTC, AlexKozhan commented on himiya.py
> +class Himiya:
fixed

2024-06-21 19:03 UTC, Stml89 commented
Please, merge ALL previous PRs

2024-06-21 19:09 UTC, Stml89 approved these changes

2024-06-23 19:07 UTC, AlexKozhan commented
> Please, merge ALL previous PRs
i will

2024-07-09 17:58 UTC, merged