Homework13: Alexey Kozhan
AlexKozhan/mypymar2024 pull request #17
Opened 2024-06-13 12:21 UTC by AlexKozhan

Homework13 is done in 2 files

2024-06-22 21:58 UTC, Stml89 requested changes

2024-06-22 21:58 UTC, Stml89 commented on calculator.py
Looks like the program won’t calc, e.g.:
1/ 2 ** 3 - 1
2/ 2 + 2 * 2

2024-06-22 21:58 UTC, Stml89 commented on files.py
> +                               f"{average_grade:.2f}\n")
```suggestion
        # Append statistics to the file
        with open(file_name, 'a', encoding='utf-8') as file:
            file.write("\nStatistics:\n")
            file.write(f"Total number of students: {total_students}\n")
            for group, count in group_counts.items():
                average_grade = group_sums[group] / count
                file.write(f"Number of students in Group {group}: "
                           f"{count}\n")
                file.write(f"Average grade for Group {group}: "
                           f"{average_grade:.2f}\n")
```

2024-06-23 19:26 UTC, AlexKozhan commented on calculator.py
fixed

2024-06-27 20:30 UTC, Stml89 approved these changes

2024-07-09 17:57 UTC, merged